baseurl = "http://nataliadronova.com/"
languageCode = "en-US"
title = "Natalia Dronova"
# Enable comments by entering your Disqus shortname
# disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""
theme = "hugo-sustain-master"

[permalinks]
  post = "/:year/:month/:day/:slug"

[params]
  avatar = "profile.jpg"
  author = "Natalia Dronova"
  description = "Describe your website"

  # Custom assets can be linked with their paths relative to static/
  custom_css = []
  custom_js  = []

[params.social]
  Github        = "ndronova"
  Email         = "ndronova04@gmail.com"
  LinkedIn      = "nataliadronova"


## Main Menu
[[menu.main]]
  name = "home"
  identifier = "home"
  weight = 100
  url = "/index.html/"
  [[menu.main]]
  name = "blog"
  weight = 200
  identifier = "blog"
  url = "/blog/"

